Chirag4904/timetable

server/src/models/subjects.model.js
also i freakin hate mongodb 😤😤
=> alloted teachers for the sub are returned when calling the sub api

server/src/app.js
Removed the comment of using index.html file which is not being used now as frontend is fully separate now.
=> removed unnecessary comments

client/svelte-timetable/src/App.svelte, client/svelte-timetable/src/components/Teacher Components/Teacher.svelte, client/svelte-timetable/src/components/Teacher Components/TeacherScreen.svelte, client/svelte-timetable/src/components/Teacher Components/TeacherSubjectsInfo.svelte
On visiting any teacher the admin/user is now able to see which subjects are allotted to that teacher and for how much time.
=> Allotted subjects visible on visiting teacher Fix #50

client/svelte-timetable/src/components/Teacher Components/TeacherSubjectsInfo.svelte
UI update for Teacher Subject Info screen.
=> Teacher subject Info screen ui update Fix #39

client/svelte-timetable/src/components/Navbar.svelte
Subject and teacher div are clickable now
=> Subject/teacher div clickable now Fix #59

server/src/routes/general/gen-api.controller.js
Total hours calculation which might come in handy when adding subjects in future.
=> total hours calculation

client/svelte-timetable/src/components/Subject Components/SubjectInfo.svelte, client/svelte-timetable/src/components/Subject Components/SubjectPref.svelte, server/src/routes/general/gen-api.controller.js
Shifted calculation of total hours from BE to FE.
=> Calculation of total hours moved to frontend

client/svelte-timetable/package-lock.json, package.json, server/package-lock.json
Added script to install all dependencies for whole project at once.
=> Able to install all dep at once Fix #46

client/svelte-timetable/package-lock.json, package-lock.json, package.json, server/package-lock.json
=> infinite installing bug fixed Fix #46

.github/workflows/project.yml
Support to add PR to project board
=> support for PR

client/svelte-timetable/src/components/Subject Components/Subject.svelte, client/svelte-timetable/src/components/Subject Components/SubjectScreen.svelte
=> Dynamic subject name and truncate Fix #85

client/svelte-timetable/src/components/Subject Components/SubjectInfo.svelte, client/svelte-timetable/src/components/Subject Components/SubjectPref.svelte, client/svelte-timetable/src/components/Subject Components/SubjectScreen.svelte, client/svelte-timetable/src/components/Teacher Components/AddTeacher.svelte, package-lock.json, package.json, server/src/models/subjects.model.js, server/src/models/subjects.mongo.js, server/src/routes/subjects/subjects.controller.js, server/src/routes/subjects/subjects.router.js
Admin is now able to add any teacher to any subject
=> bug fix and Add teacher support  #88, #89

client/svelte-timetable/src/app.css, client/svelte-timetable/src/components/Subject Components/SubjectInfo.svelte, client/svelte-timetable/src/components/Subject Components/SubjectPref.svelte, client/svelte-timetable/src/components/Subject Components/SubjectScreen.svelte, client/svelte-timetable/src/components/Teacher Components/AddTeacher.svelte
=> Subject info ui update for website

client/svelte-timetable/src/components/Subject Components/Subject.svelte, client/svelte-timetable/src/components/Teacher Components/DropDown.svelte, client/svelte-timetable/src/components/Teacher Components/TeacherSubjectsInfo.svelte, package-lock.json, package.json
=> Teacher Updated Very Beautiful UI

client/svelte-timetable/src/components/Subject Components/SubjectInfo.svelte, client/svelte-timetable/src/components/Subject Components/SubjectPref.svelte, client/svelte-timetable/src/components/Teacher Components/DropDown.svelte, client/svelte-timetable/src/components/Teacher Components/EditTeacher.svelte, client/svelte-timetable/src/components/Teacher Components/TeacherSubjectsInfo.svelte
ui update 
logic for remaining subject hours (not implemented)
=> made values dynamic in dropdown

server/.gitignore, server/migrations/1668881933291-add-subject-remaininghours.js, server/migrations/1668891822509-add-timestamps-allotment.js, server/package-lock.json, server/package.json, server/src/app.js, server/src/models/allotment.mongo.js, server/src/models/subjects.model.js, server/src/models/subjects.mongo.js, server/src/routes/subjects/subjects.controller.js, server/src/server.js, server/src/services/migrate-cli-mongodb-store.js, server/src/services/mongo.js, server/src/services/monogdb-migrations.js, server/template/migration-template.js
add logging using `morgan` that also displays the reponse time it took
PS: this PR contains commits from #101
=> add logging to backend

server/.gitignore, server/migrations/1668881933291-add-subject-remaininghours.js, server/migrations/1668891822509-add-timestamps-allotment.js, server/package-lock.json, server/package.json, server/src/models/allotment.mongo.js, server/src/models/subjects.model.js, server/src/models/subjects.mongo.js, server/src/routes/subjects/subjects.controller.js, server/src/server.js, server/src/services/migrate-cli-mongodb-store.js, server/src/services/mongo.js, server/src/services/monogdb-migrations.js, server/template/migration-template.js
whenever you hit the `/subject` api, first a function is called which computes the allocated hours for all the subjects (that have been alloted), after that the normal aggregate function is called, which also calculated `remainingHours` and sends the response back
i have left notes and some article links in case you're interested in what im doing
PS: this pr also includes commits from #100 
let me know if there are any errors you find in the api call
closes #98
=> `remainingHours` are returned alongwith `allotedHours` when calling the subjects api

client/svelte-timetable/package-lock.json, client/svelte-timetable/src/components/Subject Components/SubjectInfo.svelte, client/svelte-timetable/src/components/Subject Components/SubjectPref.svelte, client/svelte-timetable/src/components/Teacher Components/DropDown.svelte, client/svelte-timetable/src/components/Teacher Components/EditTeacher.svelte, server/package-lock.json
Remaining hours now visible in every subject
Alert if the teacher is assigned to 2 or more subjects
Redirect from teacherinfo to subject screen
=> New features added  #107

client/svelte-timetable/src/components/Teacher Components/EditTeacher.svelte, package-lock.json, package.json
=> alert teacher bugfix

client/svelte-timetable/src/components/Teacher Components/TeacherSubjectsInfo.svelte, package-lock.json, package.json
=> the dp is now dynamic

Docker/Dockerfile.frontend, Dockerfile, docker-compose.yml, nginx.conf, package-lock.json, package.json
Co-authored-by: Prasaanth-Vallabhan <prasaanthvallabhan@gmail.com>
dockerise go brrrrrrrr
=> frontend is now a separate container/image
